# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SSRS\PycharmProjects\HW_helper\app\view\layout.ui'
#
# Created: Thu Feb 23 17:33:44 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(904, 641)
        font = QtGui.QFont()
        font.setPointSize(9)
        Form.setFont(font)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 911, 641))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_float = QtGui.QWidget()
        self.tab_float.setObjectName("tab_float")
        self.groupBox = QtGui.QGroupBox(self.tab_float)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 861, 591))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_mem_like = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_mem_like.setGeometry(QtCore.QRect(20, 110, 341, 31))
        self.lineEdit_mem_like.setText("")
        self.lineEdit_mem_like.setObjectName("lineEdit_mem_like")
        self.lineEdit_float_input = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_float_input.setGeometry(QtCore.QRect(20, 50, 341, 31))
        self.lineEdit_float_input.setText("")
        self.lineEdit_float_input.setObjectName("lineEdit_float_input")
        self.label_float = QtGui.QLabel(self.groupBox)
        self.label_float.setGeometry(QtCore.QRect(20, 30, 72, 16))
        self.label_float.setObjectName("label_float")
        self.label_mem = QtGui.QLabel(self.groupBox)
        self.label_mem.setGeometry(QtCore.QRect(20, 90, 341, 16))
        self.label_mem.setObjectName("label_mem")
        self.label_warn = QtGui.QLabel(self.groupBox)
        self.label_warn.setGeometry(QtCore.QRect(100, 90, 261, 16))
        self.label_warn.setText("")
        self.label_warn.setObjectName("label_warn")
        self.lineEdit_return_float = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_return_float.setGeometry(QtCore.QRect(20, 170, 341, 31))
        self.lineEdit_return_float.setObjectName("lineEdit_return_float")
        self.label_appr = QtGui.QLabel(self.groupBox)
        self.label_appr.setGeometry(QtCore.QRect(20, 150, 72, 15))
        self.label_appr.setObjectName("label_appr")
        self.tabWidget.addTab(self.tab_float, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 871, 591))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_fd_mem_like = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_fd_mem_like.setGeometry(QtCore.QRect(30, 180, 341, 31))
        self.lineEdit_fd_mem_like.setText("")
        self.lineEdit_fd_mem_like.setObjectName("lineEdit_fd_mem_like")
        self.lineEdit_fd_input = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_fd_input.setGeometry(QtCore.QRect(30, 60, 341, 31))
        self.lineEdit_fd_input.setText("")
        self.lineEdit_fd_input.setObjectName("lineEdit_fd_input")
        self.label_fd_input = QtGui.QLabel(self.groupBox_2)
        self.label_fd_input.setGeometry(QtCore.QRect(30, 40, 72, 15))
        self.label_fd_input.setObjectName("label_fd_input")
        self.label__fd_mem_like = QtGui.QLabel(self.groupBox_2)
        self.label__fd_mem_like.setGeometry(QtCore.QRect(30, 160, 341, 16))
        self.label__fd_mem_like.setObjectName("label__fd_mem_like")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(110, 40, 91, 16))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.lineEdit_return_fd = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_return_fd.setGeometry(QtCore.QRect(30, 240, 341, 31))
        self.lineEdit_return_fd.setObjectName("lineEdit_return_fd")
        self.label_return_fd = QtGui.QLabel(self.groupBox_2)
        self.label_return_fd.setGeometry(QtCore.QRect(30, 220, 72, 15))
        self.label_return_fd.setObjectName("label_return_fd")
        self.lineEdit_dn_input = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_dn_input.setGeometry(QtCore.QRect(30, 120, 101, 31))
        self.lineEdit_dn_input.setObjectName("lineEdit_dn_input")
        self.lineEdit_fn_input = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_fn_input.setGeometry(QtCore.QRect(270, 120, 101, 31))
        self.lineEdit_fn_input.setObjectName("lineEdit_fn_input")
        self.label_dn_input = QtGui.QLabel(self.groupBox_2)
        self.label_dn_input.setGeometry(QtCore.QRect(30, 100, 72, 15))
        self.label_dn_input.setObjectName("label_dn_input")
        self.label_fn_input = QtGui.QLabel(self.groupBox_2)
        self.label_fn_input.setGeometry(QtCore.QRect(270, 100, 72, 15))
        self.label_fn_input.setObjectName("label_fn_input")
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton_exit = QtGui.QPushButton(Form)
        self.pushButton_exit.setGeometry(QtCore.QRect(872, 0, 31, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_min = QtGui.QPushButton(Form)
        self.pushButton_min.setGeometry(QtCore.QRect(840, 0, 31, 28))
        self.pushButton_min.setObjectName("pushButton_min")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "IEEE754 浮点数存储方式", None, QtGui.QApplication.UnicodeUTF8))
        self.label_float.setText(QtGui.QApplication.translate("Form", "浮点数↓", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mem.setText(QtGui.QApplication.translate("Form", "符合IEEE754标准时，浮点数在内存中的存储格式↓", None, QtGui.QApplication.UnicodeUTF8))
        self.label_appr.setText(QtGui.QApplication.translate("Form", "约等于↓", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_float), QtGui.QApplication.translate("Form", "浮点数转换", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "定点数存储方式", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fd_input.setText(QtGui.QApplication.translate("Form", "定点数↓", None, QtGui.QApplication.UnicodeUTF8))
        self.label__fd_mem_like.setText(QtGui.QApplication.translate("Form", "定点数点数在内存中的存储格式↓", None, QtGui.QApplication.UnicodeUTF8))
        self.label_return_fd.setText(QtGui.QApplication.translate("Form", "约等于↓", None, QtGui.QApplication.UnicodeUTF8))
        self.label_dn_input.setText(QtGui.QApplication.translate("Form", "整数位数↓", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fn_input.setText(QtGui.QApplication.translate("Form", "小数位数↓", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "定点数转换", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exit.setText(QtGui.QApplication.translate("Form", "×", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min.setText(QtGui.QApplication.translate("Form", "_", None, QtGui.QApplication.UnicodeUTF8))

